### ISSUE TITLE
How to reproduce the performance on Cora with incomplete edges?

### ISSUE THREAD

**Issue by llan-ml** [lucfra/LDS-GNN#5]
Hi @lucfra ,

Thanks for your great work!

I ran the following code
```shell
python lds.py -m lds -e 100 -d cora
```
and only got about 70% test accuracy after the grid search. However, the reported performance in Figure 2 of your paper is higher than 80% with very low variance.

I did not modify any code in this repo. Can you give me some advice to reproduce the results?

**Comment by lucfra** [comment]
Hi @llan-ml, 

thanks for your message and interest in our work!

There is indeed a mismatch between the x-axis of Figure 2, which reports the percentage of **retained** edges and the parameter `-e` in the code which, instead, sets the percentage of **missing** edges. 
So 
```python lds.py -m lds -e 100 -d cora```
runs the code with 100% of missing edges, hence empty adjacency matrix.  You should run 
```python lds.py -m lds -e 0 -d cora```
to reproduce the results for the last point (100% retained edges) of Figure 2.

I will add a comment on the code to clarify this!

Cheers, 
Luca

**Comment by llan-ml** [comment]
Thanks for your reply. The issue is solved!
