### ISSUE TITLE
About gpu

### ISSUE THREAD

**Issue by YoungTaoD** [lucfra/LDS-GNN#7]
Hi, i think your code is pretty good, but i wonder if there is an gpu-version?

**Comment by lucfra** [comment]
Hi @dyt0414 , 

thank you for your message. The code as it is should run an the GPU if you have one available. Are you having troubles with that? 

Cheers, 
Luca

**Comment by YoungTaoD** [comment]
Hi, i wonder is there requirements on GPU device and cuda version? I use RTX 2080 and my cuda version is 9.1, could the code can directly run on my gpu and cuda?

**Comment by lucfra** [comment]
I think so. 
You can check by running it and see if GPUs are being used e.g. with nvidia-smi. 

Cheers, 
Luca

**Comment by YoungTaoD** [comment]
Thank you very much for your patience！I have solved it luckly~

**Comment by lucfra** [comment]
Great! Have a nice day.

Cheers, 
Luca
