### ISSUE TITLE
About LSTM

### ISSUE THREAD

**Issue by YoungTaoD** [lucfra/LDS-GNN#8]
Hi, i think your code is very innovation, and i try to modify it with adding lstm to the gcn model, which is in models.py, but it turns back an error "TypeError: Second-order gradient for while loops not supported.". So, could you give me some suggestions>

**Comment by lucfra** [comment]
Hi @dyt0414, 

Thanks for the message. Yes, this is a known "missing feature'" of tensorflow 1, I am not sure if they have implemented it in tensorflow 2. To circumvent the problem you might try to implement an LSTM model by yourself, using only basic operations, and unrolling it "manually" for a fixed number of steps. 
Some time ago, I have done it with a simpler RNN model, but it should be feasible also with an LSTM architecture. However, this requires a  certain amount of work, and I'd advise you - should you want to try - to always verify the custom model against a standard implementation!
Also, computationally speaking, it's very likely that the custom model will run slower/require more memory (so you might have to settle for a smallish model to make everything run in reasonable time).

Cheers, 
Luca

PS you might have more luck with pytorch for these kinds of things... I'd suggest taking a look at that as well, although I cannot point you to any specific repo.

**Comment by YoungTaoD** [comment]
I run as static_rnn successfully, but it run typically slow.
Thanks for your guidance and patience!
If it is possible, i wonder could you give me an email address for your work? I have some academic questions about machine learning should be asked for your help.

**Comment by lucfra** [comment]
Hi @dyt0414 . 

You can write to me at luca.franceschi.16@ucl.ac.uk

Luca
